remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme

title: WaVer
description: A software dedicated to study combustion instability in hybrid rockets. It was developed my researchers at University of Brasilia.
show_downloads: true
github:
  waver_zip: http://waver-dev.github.io/WaVer.zip
